### ISSUE TITLE
Storing "special" characters ends up with html soup in title

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial-admin#11]
setting "Mina's Social" as title
it's rendered as: `Mina&#39;s Social`

this doesn't happen in the short description.
no idea where the description ends up in, so, 🤷🏻‍♀️

**Comment by igalic** [comment]
ref: https://github.com/superseriousbusiness/gotosocial/pull/607

**Comment by f0x52** [comment]
fixed in gotosocial main
