### ISSUE TITLE
Instance must be specified with https:// to login

### ISSUE THREAD

**Issue by 6k27f** [superseriousbusiness/gotosocial-admin#7]
On the OAUTH Login screen, if the user specifies the instance with https:// (https://gts.superseriousbusiness.org) it works. However, if the user specifies just the domain without the protocol (gts.superseriousbusiness.org), it does the following:
1. Clicking "Authenticate" appears to do nothing. (Presumably some error occurs.)
2. After clicking "Authenticate", if the user refreshes or closes the tab or browser without clearing cookies and opens it again, the page just says "processing oauth..." The user must clear cookies to be able to try again.

There's no clear feedback, so if you don't know to start the instance domain with https:// it just seems like the admin panel doesn't work at all.

gotosocial-admin should handle the case that the user does not specify the https://, either by inferring the protocol (like most Fediverse software does) or by catching the error and informing the user of the issue.

**Comment by 6k27f** [comment]
(This came up because I set up the admin panel on a separate domain from the GoToSocial instance, so the admin panel login form didn't autofill the instance.)

**Comment by igalic** [comment]
i can't proceed with the OAuth, for the same reason:
```
Unhandled rejection TypeError: URL constructor: soc.eena.me is not a valid URL.
    authorizeToken@http://127.0.0.1:8000/bundle.js:36779:15
    callback@http://127.0.0.1:8000/bundle.js:36772:12
    [22]</App/</<@http://127.0.0.1:8000/bundle.js:37290:30
From previous event:
    [22]</App/<@http://127.0.0.1:8000/bundle.js:37289:15
    invokePassiveEffectCreate@http://127.0.0.1:8000/bundle.js:33155:20
    callCallback@http://127.0.0.1:8000/bundle.js:13613:14
    invokeGuardedCallbackDev@http://127.0.0.1:8000/bundle.js:13662:16
    invokeGuardedCallback@http://127.0.0.1:8000/bundle.js:13724:31
    flushPassiveEffectsImpl@http://127.0.0.1:8000/bundle.js:33242:30
    unstable_runWithPriority@http://127.0.0.1:8000/bundle.js:3591:12
    runWithPriority$1@http://127.0.0.1:8000/bundle.js:20944:10
    flushPassiveEffects@http://127.0.0.1:8000/bundle.js:33115:14
    [7]</</</commitBeforeMutationEffects/<@http://127.0.0.1:8000/bundle.js:32992:11
    workLoop@http://127.0.0.1:8000/bundle.js:3540:42
    flushWork@http://127.0.0.1:8000/bundle.js:3513:14
    performWorkUntilDeadline@http://127.0.0.1:8000/bundle.js:3280:48 bundle.js:5477:21
```

this is happening *after* i corrected the URI to contain `https://`

**Comment by f0x52** [comment]
fixed in https://github.com/superseriousbusiness/gotosocial/pull/634/commits/11ac9e2fd282eeee1600a284536497f30c62c08c (which is where the admin panel will move to)
