### ISSUE TITLE
Tag the current version of gotosocial-admin

### ISSUE THREAD

**Issue by Hukadan** [superseriousbusiness/gotosocial-admin#9]
Hi,
I plan to package `gotosocial-admin`. However, to do so, it would be handy if there was a version tag available. Could you tag the current version?
Thank you.

**Comment by f0x52** [comment]
we're moving the admin panel into the main repo (https://github.com/superseriousbusiness/gotosocial/pull/634), and as such it'll be versioned with the general releases
